### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by aoi276** [aoi276/protospace-34261#1]
https://protospace-34261.herokuapp.com/

**Comment by snkw-works** [comment]
@aoi276 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるよう修正しましょう**
現状、「こんにちは、〇〇」と表示されています。

- [ ] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できるよう修正しましょう**
現状、自身の投稿したプロトタイプの編集ボタンをクリックしても編集ページに遷移できない状態です。

- [ ] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるよう修正しましょう**
現状、コメントフォームを空のまま送信すると、エラー画面に遷移してしまいます。
<img width="762" alt="スクリーンショット 2021-05-02 16 58 03" src="https://user-images.githubusercontent.com/54050089/116806379-9386d380-ab67-11eb-9eca-71aad8aa55b4.png">

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
現状、トップページの投稿者名、ユーザー詳細ページの投稿者名をクリックすると、異なるユーザー詳細ページに遷移してしまいます。
<img width="1440" alt="スクリーンショット_2021-05-02_17_03_44" src="https://user-images.githubusercontent.com/54050089/116806562-e319cf00-ab68-11eb-84fd-0d92a9cc3642.png">
<img width="1440" alt="スクリーンショット_2021-05-02_17_06_23" src="https://user-images.githubusercontent.com/54050089/116806565-e745ec80-ab68-11eb-9e86-255a9bb37c5b.png">

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
現状、そのユーザーが投稿したプロトタイプが正しく表示されておりません。
※画像はテストユーザー2の詳細ページですが、投稿していないプロトタイプが表示されています。
<img width="1440" alt="スクリーンショット 2021-05-02 17 09 51" src="https://user-images.githubusercontent.com/54050089/116806618-50c5fb00-ab69-11eb-806e-587b835ccca7.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takumi0530** [comment]
@aoi276 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
